### PR TITLE
Fixed incorrect type of digestAlgorithm

### PR DESCRIPTION
**Pull request by vinsonmixcare**

### CODE REVIEW

**Comment by freekmurze** [comment]
Seems like this is failing on older version, could you take a look?

**Comment by vinsonmixcare** [comment]
> Seems like this is failing on older version, could you take a look?

Oh sorry that did not test in PHP 7.4.

According to https://www.php.net/manual/en/openssl.signature-algos.php, type of OPENSSL_ALGO_SHA512 is int since PHP 5.4.8. So I changed it to integer.

**Comment by freekmurze** [comment]
I'm going to leave things as they are for now, as it currently seems to be working.

**Comment by vinsonmixcare** [comment]
It is weird that I got this error:

Spatie\Crypto\Rsa\KeyPair::__construct(): Argument #1 ($digestAlgorithm) must be of type string, int given

**Comment by freekmurze** [comment]
Could you PR a failing test for us to fix?

**Pull request closed without merging**
